`timescale 1ns / 1ps

// update: currently will do tiling here since there is still no DMA (i am the DMA)
// and then i need to implement tiling to feed to the routers 
module tb_top_systolic_array;

    parameter DATA_WIDTH = 8;
    parameter N = 8;

    // Clock and reset
    logic clk;
    logic nrst;

    // Inputs to top module
    logic [0:N-1][DATA_WIDTH-1:0] ifmap;
    logic [0:N-1][DATA_WIDTH-1:0] weight;

    logic        wr_en;
    logic [15:0] wr_addr;
    logic [31:0] wr_data;
    
    // Outputs
    logic [3:0] led; 
    logic [0:N-1][DATA_WIDTH*2-1:0] ofmap;
    
    // Handshake Wires
    logic tb_ir_ready = 0;
    logic tb_wr_ready = 0;
    logic tb_ir_done  = 0;
    logic tb_wr_done  = 0;
    logic tb_or_done  = 0;
    
    // Storage for the .mem files of person_detection.tflite
    // the .mem files have 1 value per line
    /*logic [DATA_WIDTH-1:0] weight_mem_raw [0:4095]; // depth of 4096
    logic [DATA_WIDTH-1:0] ifmap_mem_raw [0:4095];
    logic [DATA_WIDTH*2-1:0] bias_mem [0:511];*/
    // 96x96 = 9216 lines. Each line has 8 values (one for each array column)
    logic [DATA_WIDTH-1:0] ifmap_8ch_mem [0:9215][0:7]; 
    logic [DATA_WIDTH-1:0] weight_mem_raw [0:71];       // 8 channels * 9 weights
    logic [DATA_WIDTH-1:0] golden_8ch_mem [0:2303][0:7]; // 48x48 output, stride 2
    logic [DATA_WIDTH*2-1:0] bias_mem [0:511];
    
    // pointer for current byte index
    integer weight_pointer = 0;
    integer ifmap_pointer = 0;
    integer golden_ptr = 0;
    integer error_count = 0;
    
    initial begin
        // Load the one-value-per-line .mem files
        /*$readmemh("MobilenetV1_Conv2d_0_depthwise_weights_read.mem", weight_mem_raw);
        $readmemh("video_input_fake.mem", ifmap_mem_raw);
        $readmemh("MobilenetV1_MobilenetV1_Conv2d_0_Conv2D_bias.mem", bias_mem);
        $display("--- Person Detection Data Loaded ---");*/
        // Load the 8-channel .mem files generated by Python
        $readmemh("MobilenetV1_Conv2d_0_depthwise_weights_read.mem", weight_mem_raw);
        $readmemh("video_input_96x96_bnw_1.mem", ifmap_8ch_mem);
        $readmemh("golden_output_ch0_1.mem", golden_8ch_mem);
        $readmemh("MobilenetV1_MobilenetV1_Conv2d_0_Conv2D_bias.mem", bias_mem);
        $display("--- Person Detection Data Loaded for Layer 0, Stride 2 ---");
    end
    
    // FEEDING THE LOGIC (Temporary DMA) btw channel refers to the depth of the layers
    always @(posedge clk) begin
        if(uut.tile_ctrl.o_wr_pop_en && uut.tile_ctrl.o_ir_pop_en) begin 
            // IFMAP: Load 8 channels from memory into the array's 8 rows
            for (int k = 0; k < N; k++) begin
                ifmap[k] <= ifmap_8ch_mem[ifmap_pointer][k];
            end
            
            // 2. Zero padding for the rest of the channels (1 to 7)
            /*for (int k = 1; k < N; k++) begin
                ifmap[k] <= 8'h00;
            end*/
            
            // 3. Weight Logic: one weight per output filter
            /*for (int j = 0; j < N; j++) begin
                weight[j] <= weight_mem_raw[weight_pointer + j];
            end*/
            // 3. Weight Logic: Mode Dependent
            if (uut.layer_type == 1'b0) begin : DW_WEIGHTS
                // Depthwise: We only need the NEXT weight in the kernel
                for (int j = 0; j < N; j++) begin
                    weight[j] <= weight_mem_raw[(j * 9) + weight_pointer]; 
                    // column j gets weight from channel j (offset of 9 weights per channel)
                end
                weight_pointer <= (weight_pointer == 8) ? 0 : weight_pointer + 1; // change to go back to 0
            end
            else begin : PW_WEIGHTS
                // Pointwise: Flash 8 weights at once (one per filter)
                for (int j = 0; j < N; j++) begin
                    weight[j] <= weight_mem_raw[weight_pointer + j];
                end
                weight_pointer <= weight_pointer + N; // Increment by 8
            end
                       
            // 4. Update pointers
            /*ifmap_pointer  <= ifmap_pointer + 1;  // Advance by 1 pixel for B&W
            weight_pointer <= weight_pointer + N; // Advance by N weights*/
            // 4. Update IFMAP pointer
            ifmap_pointer  <= ifmap_pointer + 1; // get all the pixels
            
        end else if (uut.tile_ctrl.state == 3'd0) begin
            // Reset pointers when in IDLE
            ifmap_pointer <= 0;
            weight_pointer <= 0;
            golden_ptr <= 0;
            error_count <= 0;
            tb_ir_ready = 0;
            tb_wr_ready = 0;
            tb_ir_done  = 0;
            tb_wr_done  = 0;
            tb_or_done  = 0;
        end      
    end
    
    // COMPARISON USING THE PYTHON STUFF:
    always @(posedge clk) begin
        if (uut.psum_out_en && uut.o_state == 3'd5) begin 
            // Check each of the 8 channels (shape is giving 8 channels) for this output pixel
            for (int i = 0; i < 8; i++) begin
                if (ofmap[i] !== golden_8ch_mem[golden_ptr][i]) begin
                    $display("ERROR at Output %d, Ch %d: Expected %h, Got %h", 
                              golden_ptr, i, golden_8ch_mem[golden_ptr][i], ofmap[i]);
                    error_count <= error_count + 1;
                end
            end
            golden_ptr <= golden_ptr + 1;
        end
    end

    string state_name;
    initial begin
        $display("--- Monitoring Control Registers ---");
        forever begin
            // Trigger whenever registers OR the internal FSM state changes
            @(uut.layer_type or uut.C_in or uut.start_reg or uut.done or uut.tile_ctrl.state);
            // Translate the numeric state to a readable string
            case (uut.tile_ctrl.state)
                3'd0: state_name = "IDLE";
                3'd1: state_name = "CLEAR";
                3'd2: state_name = "ACTIVATION_ROUTING";
                3'd3: state_name = "FIFO_POP";
                3'd4: state_name = "COMPUTE";
                3'd5: state_name = "OUTPUT_ROUTING";
                3'd7: state_name = "WAIT_FOR_ROUTE";
                2'd8: state_name = "OUTPUT_STAGE";
                default: state_name = "UNKNOWN";
            endcase
/*
            $display("[%0t ns] SYSTEM STATUS UPDATE:", $time);
            $display("       FSM State:  %s (%0d)", state_name, uut.tile_ctrl.state);
            $display("       Layer Type: %s", uut.layer_type ? "POINTWISE (1)" : "DEPTHWISE (0)");
            $display("       C_in:       %0d", uut.C_in);
            $display("       Start Reg:  %b", uut.start_reg);
            $display("       Done:  %b", uut.done);
            $display("------------------------------------");*/
        end
    end

    // --------------------------------------------------
    // DUT
    // --------------------------------------------------
    top_systolic_array #(
        .DATA_WIDTH(DATA_WIDTH),
        .N(N)
    ) uut (
        .clk(clk),
        .nrst(nrst),
        .wr_en(wr_en),
        .wr_addr(wr_addr),
        .wr_data(wr_data),
        
        .ifmap(ifmap),
        .weight(weight),
        
        .led(led),
        .ofmap(ofmap),
        
        // fake wires
        .i_ir_ready(tb_ir_ready),
        .i_wr_ready(tb_wr_ready),
        .i_ir_done(tb_ir_done),
        .i_wr_done(tb_wr_done),
        .i_or_done(tb_or_done)
        
    );

    // --------------------------------------------------
    // Clock generator
    // --------------------------------------------------
    initial begin
        clk = 0;
        forever #5 clk = ~clk;
    end
    // --------------------------------------------------
    // Reset
    // --------------------------------------------------
    initial begin
        // Initialize
        nrst  = 0;
        wr_en = 0; 
        wr_addr = 0; 
        wr_data = 0;
        ifmap  = 0; 
        weight = 0;
        
        #20;
        nrst = 1;
        repeat (5) @(posedge clk);
        
        // Step 1: Write Registers (Moves State from IDLE -> IDLE)
        $display("Configuring the Layer...");
        write_reg(16'h00, 32'h0); // layer type is 0 (DW)
        write_reg(16'h04, 32'd9);  // Cin 
        write_reg(16'h10, 32'd5); // Bias
        write_reg(16'h14, 32'd11); // quant shift
        write_reg(16'h18, 32'd256); // quant mult
        write_reg(16'h20, 32'd2); // stride is actually 2
        write_reg(16'h1C, 32'h1); // Start bit
/*        
        // Fake Base Addresses:
        $display("Setting Dummy Base Addresses...");
        write_reg(8'h08, 32'hA000); // weight_base_addr
        write_reg(8'h0C, 32'hB000); // ifmap_base_addr*/
        
        // Step 3: Exit ACTIVATION_ROUTING -> FIFO POP
        wait(uut.tile_ctrl.state == 3'd2);
        @(posedge clk);
        tb_ir_ready <= 1'b1; 
        tb_wr_ready <= 1'b1;
        $display("[%0t ns] Handshake Good, Routers are Ready", $time);
        
        // WAIT FOR THE ENTIRE IMAGE TO BE TRANSFERRED 
        wait(ifmap_pointer >= 9215); 
        $display("[%0t ns] Input Image Stream Complete", $time);
        tb_ir_done = 1; tb_wr_done = 1;
        @(posedge clk);
        tb_ir_done = 0; tb_wr_done = 0;
        
        // Step 4: Exit FIFO_POP  -> COMPUTE
        wait(uut.tile_ctrl.state == 3'd3); // wait until the pointers say the data is snet
        if (uut.layer_type == 0) begin
            wait(ifmap_pointer >= 9); // DW 3x3
        end else begin
            wait(ifmap_pointer >= uut.C_in); // PW
        end 
        @(posedge clk); // done signal then clear
        tb_ir_done = 1; 
        tb_wr_done = 1;
        @(posedge clk); // clear
        tb_ir_done = 0; 
        tb_wr_done = 0;
        
        
        wait(uut.tile_ctrl.state == 3'd5); // Wait for OUTPUT_ROUTING
        $display("[%0t ns] Conv Done. Signaling Output...", $time);
        #100;
        tb_or_done = 1; // Trigger the transition back to IDLE
        #20;
        tb_or_done = 0;

        $display("[%0t ns] Draining 2304 pixels...", $time); // which is the 48x48
        while (golden_ptr < 2304) begin
            @(posedge clk);
            if (uut.psum_out_en) begin
                tb_or_done <= 1; // Keep the output router open
            end else begin
                tb_or_done <= 0;
            end
        end
        
        // Step 6: Wait for Control Register Auto-Clear
        wait(uut.done == 1);
        $display("Simulation Finished. Total Errors: %0d", error_count);
        #500;
        $finish;
    end
    // Task for writing to registers (some random values)
    task write_reg(input [15:0] addr, input [31:0] data);
        begin
            @(posedge clk);
            wr_en = 1;
            wr_addr = addr;
            wr_data = data;
            @(posedge clk);
            wr_en = 0;
        end
    endtask
    
    // Monitor Control Registers Printing on the Tcl Console
 /*   initial begin
        $display("--- Monitoring Control Registers ---");
        forever begin
            // Wait for any of the control signals to change
            @(uut.layer_type or uut.C_in or uut.start_reg or uut.done);
            
            $display("[%0t ns] REG UPDATE:", $time);
            $display("       Layer Type: %s", uut.layer_type ? "POINTWISE (1)" : "DEPTHWISE (0)");
            $display("       C_in:       %0d", uut.C_in);
            $display("       Start Reg:  %b", uut.start_reg);
            $display("       Done Flag:  %b", uut.done);
            $display("------------------------------------");
        end
    end*/
    
    // print something everytime there is a change in the variable or behavior
    // i also might turn off record waveform
    initial begin
        $monitor("Time=%0t | State=%s | if_ptr=%0d | golden_ptr=%0d | Errors=%0d", 
                 $time, state_name, ifmap_pointer, golden_ptr, error_count);
    end
endmodule